name: "Build common"

on:
  workflow_call:
    secrets:
      QUIC_GO_DEPLOY_KEY:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.list-files.outputs.files }}

    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check out private quic-go dependency
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: onesyue/quic-go
          ref: 870c4d4ab48b1a9d8a1f9e2bc82f992b074a6ea1
          path: .ci/quic-go
          ssh-key: ${{ secrets.QUIC_GO_DEPLOY_KEY }}
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "1.26.6"
          cache-dependency-path: |
            core/go.sum
            extras/go.sum
            app/go.sum

      - name: Use checked-out private dependency
        run: go work edit -replace=github.com/apernet/quic-go=./.ci/quic-go

      - name: Setup uv # This is for the build script
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          version: "0.12.0"
          enable-cache: true

      - uses: nttld/setup-ndk@ed92fe6cadad69be94a966a7ee3271275e62f779 # v1.6.0
        id: setup-ndk
        with:
          ndk-version: r29
          add-to-path: false

      - name: Run build script
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          export HY_APP_PLATFORMS=$(sed 's/\r$//' platforms.txt | awk '!/^#/ && !/^$/' | paste -sd ",")
          uv run python hyperbole.py build -r

      - name: Generate hashes
        run: |
          for file in build/*; do
            sha256sum $file >> build/hashes.txt
          done

      - name: List build files
        id: list-files
        run: |
          files=$(ls -1 build/ | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "files=$files" >> $GITHUB_OUTPUT

      - name: Upload build directory
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: build-temp-${{ github.sha }}
          path: build/

  upload:
    name: Upload ${{ matrix.file }}
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJson(needs.build.outputs.files) }}
    steps:
      - name: Download build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build-temp-${{ github.sha }}

      - name: Upload ${{ matrix.file }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.file }}
          path: ${{ matrix.file }}
