name: "Build experimental branches"

on:
  push:
    branches:
      - exp/**

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    secrets:
      QUIC_GO_DEPLOY_KEY: ${{ secrets.QUIC_GO_DEPLOY_KEY }}
