name: "Build master branch"

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    secrets:
      QUIC_GO_DEPLOY_KEY: ${{ secrets.QUIC_GO_DEPLOY_KEY }}
