name: "Build release"

on:
  push:
    tags:
      - app/v*.*.*

jobs:
  build:
    uses: ./.github/workflows/build-common.yml
    secrets:
      QUIC_GO_DEPLOY_KEY: ${{ secrets.QUIC_GO_DEPLOY_KEY }}

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get version
        id: get_version
        run: |
          version=$(git describe --tags --always --match 'app/v*' | sed -n 's|app/\([^/-]*\)\(-.*\)\{0,1\}|\1|p')
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Setup uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          version: "0.12.0"
          enable-cache: true

      - name: Download build
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build-temp-${{ github.sha }}
          path: build

      - name: Upload GitHub
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: build/*

      - name: Upload CF bucket
        uses: shallwefootball/upload-s3-action@4350529f410221787ccf424e50133cbc1b52704e # v1.3.3
        with:
          aws_key_id: ${{ secrets.CF_KEY_ID }}
          aws_secret_access_key: ${{ secrets.CF_KEY }}
          aws_bucket: "hydownload"
          endpoint: "https://bea223c61d5a41250d127bd67f51dfec.r2.cloudflarestorage.com/"
          source_dir: "build"
          destination_dir: "app/${{ steps.get_version.outputs.version }}"

      - name: Publish to API
        run: |
          export HY_API_POST_KEY=${{ secrets.HY2_API_POST_KEY }}
          uv run python hyperbole.py publish
